name: Better Checkout
description: A better version of actions/checkout
author: trev

branding:
  icon: chevron-up
  color: yellow

inputs:
  token:
    description: token for checkout and git operations
    required: false
    default: ${{ github.token }}

  app-id:
    description: github app/client id
    required: false
  app_id:
    description: github app/client id
    required: false

  private-key:
    description: github private key
    required: false
  app_key:
    description: github private key
    required: false

  fetch-depth:
    description: depth for git fetch
    required: false
    default: "1"

outputs:
  token:
    description: app token
    value: ${{ steps.app.outputs.token || inputs.token }}

  name:
    description: git user name
    value: ${{ steps.github.outputs.name || steps.gitea.outputs.name }}

  email:
    description: git user email
    value: ${{ steps.github.outputs.email || steps.gitea.outputs.email }}

runs:
  using: composite
  steps:
    - name: Detect platform
      shell: bash
      run: |
        # Detect platform

        if [[ -n "${GITEA_ACTIONS}" ]]; then
          echo "PLATFORM=gitea" >> $GITHUB_ENV
        elif [[ -n "${FORGEJO_ACTIONS}" ]]; then
          echo "PLATFORM=forgejo" >> $GITHUB_ENV
        elif [[ -n "${GITHUB_ACTIONS}" ]]; then
          echo "PLATFORM=github" >> $GITHUB_ENV
        fi

    - name: Create app token
      if: ${{ env.PLATFORM == 'github' && inputs.app-id != '' && inputs.private-key != '' }}
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      id: app
      with:
        app-id: ${{ inputs.app-id || inputs.app_id }}
        private-key: ${{ inputs.private-key || inputs.app_key }}

    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ steps.app.outputs.token || inputs.token }}

    - name: Setup git user (github)
      if: ${{ env.PLATFORM == 'github' }}
      shell: bash
      id: github
      env:
        GH_TOKEN: ${{ steps.app.outputs.token || inputs.token }}
      run: |
        # Setup git user (github)

        if [[ -n "${{ steps.app.outputs.app-slug }}" ]]; then
          NAME="${{ steps.app.outputs.app-slug }}[bot]"
        else
          NAME="github-actions[bot]"
        fi

        ID=$(gh api "/users/${NAME}" --jq .id)
        EMAIL="${ID}+${NAME}@users.noreply.github.com"

        git config --local user.name "${NAME}"
        git config --local user.email "${EMAIL}"

        echo "name=${NAME}" >> "$GITHUB_OUTPUT"
        echo "email=${EMAIL}" >> "$GITHUB_OUTPUT"

        echo "git user: ${NAME} <${EMAIL}>"

    - name: Setup git user (gitea)
      if: ${{ env.PLATFORM == 'gitea' || env.PLATFORM == 'forgejo' }}
      shell: bash
      id: gitea
      run: |
        # Setup git user (gitea)

        if ! command -v jq >/dev/null 2>&1; then
          TMP_BIN=$(mktemp -d)
          curl -sSL -o "${TMP_BIN}/jq" https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64
          chmod +x "${TMP_BIN}/jq"
          export PATH=${PATH}:${TMP_BIN}
        fi

        USER=$(curl -H "Authorization: token ${{ inputs.token }}" "${{ github.server_url }}/api/v1/user" )
        NAME=$(echo "${USER}" | jq -r .login)
        EMAIL=$(echo "${USER}" | jq -r .email)

        git config --local user.name "${NAME}"
        git config --local user.email "${EMAIL}"

        echo "git user: ${NAME} <${EMAIL}>"
